//try catch

const numero1 = 50;
const numero3 = 90;


console.log(numero1);
try {
    console.log(numero2);
} catch (error) {
    console.log(error);
}

console.log(numero3);